vlib modelsim
vlib modelsim/grlib 
vlib modelsim/altera 
vlib modelsim/altera_mf 
vlib modelsim/cycloneiii 
vlib modelsim/techmap 
vlib modelsim/spw 
vlib modelsim/eth 
vlib modelsim/opencores 
vlib modelsim/gaisler 
vlib modelsim/esa 
vlib modelsim/micron 
vlib modelsim/work 
